import os
import copy
import json
import random
import numpy as np
from collections import deque
from tqdm import tqdm
import multiprocessing
import concurrent.futures
import io
import torch

def worker_execute_episode(worker_args):
    """Generates self-play data using an isolated worker process."""
    game_size, latest_model_path, mcts_class, args, game_sequence, start_fill_pct, opp_type, opp_path = worker_args
    
    # Must import inside worker to avoid pickle issues
    from game import DotsAndBoxesGame
    from model import NNetWrapper
    import copy
    import random
    
    dummy_game = DotsAndBoxesGame(size=game_size)
    nnet = NNetWrapper(dummy_game, args)
    
    # Load latest model from path safely
    state_dict = torch.load(latest_model_path, map_location='cpu', weights_only=True)
    nnet.nnet.load_state_dict(state_dict['state_dict'] if 'state_dict' in state_dict else state_dict)
    nnet.nnet.eval()
    mcts_latest = mcts_class(nnet, args)
    
    # Initialize opponent
    if opp_type == "self":
        agent_opp = None
    elif opp_type in ["best", "past"]:
        opp_net = NNetWrapper(dummy_game, args)
        opp_state_dict = torch.load(opp_path, map_location='cpu', weights_only=True)
        opp_net.nnet.load_state_dict(opp_state_dict['state_dict'] if 'state_dict' in opp_state_dict else opp_state_dict)
        opp_net.nnet.eval()
        mcts_opp = mcts_class(opp_net, args)
        def agent_opp(g, t):
            pi = mcts_opp.play(g, temp=t)
            return pi, mcts_opp.max_depth_reached
    elif opp_type == "alpha_beta_0.1s":
        from bots.alpha_beta import AlphaBetaPlayer
        baseline = AlphaBetaPlayer(name="AlphaBeta", time_limit=0.1)
        def agent_opp(g, t):
            move = baseline.get_move(copy.deepcopy(g))
            pi = np.zeros(g.N_LINES, dtype=np.float32)
            pi[move] = 1.0
            return pi, 0
    elif opp_type == "mcts_0.1s":
        from bots.mcts_x import MCTSGAgent
        baseline = MCTSGAgent(name="MCTS", time_limit=0.1)
        def agent_opp(g, t):
            move = baseline.get_move(copy.deepcopy(g))
            pi = np.zeros(g.N_LINES, dtype=np.float32)
            pi[move] = 1.0
            return pi, 0
            
    p1_is_latest = random.choice([True, False])
    
    train_examples = []
    game = DotsAndBoxesGame(size=game_size, starting_player=1)
    
    # Reverse Curriculum Logic: Pre-fill the board using the historical log sequence
    if game_sequence is not None and start_fill_pct >= 0.001:
        target_move_index = int(len(game_sequence) * start_fill_pct)
        for move in game_sequence[:target_move_index]:
            game.execute_move(move)
            
    episode_step = 0
    depths = []

    while game.is_running():
        episode_step += 1
        temp = int(episode_step < args.temp_threshold)
        
        is_latest_turn = (game.current_player == 1) == p1_is_latest
        
        if is_latest_turn or opp_type == "self":
            pi = mcts_latest.play(game, temp=temp)
            depths.append(mcts_latest.max_depth_reached)
            
            canonical_lines = game.get_canonical_lines()
            canonical_boxes = game.get_canonical_boxes()
            train_examples.append([canonical_lines, canonical_boxes, game.current_player, pi, None])
            
            action = np.random.choice(len(pi), p=pi)
        else:
            pi, depth = agent_opp(game, temp)
            if depth > 0: depths.append(depth)
            
            # We do NOT append to train_examples for opponents (unless opp_type == "self"),
            # because we only train the network on data generated by the *latest* network policy.
            action = np.random.choice(len(pi), p=pi)
            
        game.execute_move(action)

    r = game.result
    avg_depth = sum(depths) / len(depths) if depths else 0
    
    # Process final reward from perspective of player who played that turn
    final_examples = []
    for x in train_examples:
        val = r if x[2] == 1 else -r
        final_examples.append((x[0], x[1], x[3], val))
        
    return final_examples, episode_step, avg_depth

def worker_play_single(worker_args):
    """Plays a single arena match in an isolated worker process."""
    game_size, latest_model_path, pnet_bytes, mcts_class, args, p1_starts, opponent_type = worker_args
    
    from game import DotsAndBoxesGame
    from model import NNetWrapper
    import copy
    
    dummy_game = DotsAndBoxesGame(size=game_size)
    
    # Init new network (Agent 1)
    nnet = NNetWrapper(dummy_game, args)
    state_dict = torch.load(latest_model_path, map_location='cpu', weights_only=True)
    nnet.nnet.load_state_dict(state_dict['state_dict'] if 'state_dict' in state_dict else state_dict)
    nnet.nnet.eval()
    mcts1 = mcts_class(nnet, args)
    def agent1(g):
        pi = mcts1.play(g, temp=0)
        return np.argmax(pi)
        
    # Init opponent (Agent 2)
    if opponent_type == "random":
        import random
        def agent2(g):
            valid_moves = g.get_valid_moves()
            return random.choice(valid_moves) if valid_moves else None
    elif opponent_type == "alpha_beta_0.1s":
        from bots.alpha_beta import AlphaBetaPlayer
        baseline = AlphaBetaPlayer(name="AlphaBeta_0.1s", time_limit=0.1)
        def agent2(g):
            return baseline.get_move(copy.deepcopy(g))
    elif opponent_type == "mcts_0.1s":
        from bots.mcts_x import MCTSGAgent
        baseline = MCTSGAgent(name="MCTS_0.1s", time_limit=0.1)
        def agent2(g):
            return baseline.get_move(copy.deepcopy(g))
    else: # "pnet"
        pnet = NNetWrapper(dummy_game, args)
        pbuffer = io.BytesIO(pnet_bytes)
        pstate_dict = torch.load(pbuffer, weights_only=True)
        pnet.nnet.load_state_dict(pstate_dict)
        pnet.nnet.eval()
        mcts2 = mcts_class(pnet, args)
        def agent2(g):
            pi = mcts2.play(g, temp=0)
            return np.argmax(pi)
            
    game = DotsAndBoxesGame(size=game_size, starting_player=1)
    players = {1: agent1, -1: agent2} if p1_starts else {1: agent2, -1: agent1}
    
    while game.is_running():
        cur_player = game.current_player
        action = players[cur_player](game)
        game.execute_move(action)
        
    # Return 1 if agent1 won, -1 if agent2 won, 0 for draw
    if p1_starts:
        return game.result
    else:
        return -game.result


class AlphaZeroTrainer:
    def __init__(self, game_size, nnet, pnet, mcts_class, args):
        self.game_size = game_size
        self.nnet = nnet
        self.pnet = pnet
        self.MCTS = mcts_class
        self.args = args
        self.memory = deque(maxlen=self.args.maxlen_queue)
        self.train_examples_history = deque([], maxlen=self.args.keep_history_iters)
        
        # Load Reverse Curriculum Logs
        self.json_logs = []
        log_path = "logs/game_logs.jsonl"
        expected_moves = 2 * self.game_size * (self.game_size + 1)
        if os.path.exists(log_path):
            with open(log_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            record = json.loads(line)
                            moves = record.get("moves", [])
                            # Only load games that match our current board size exactly
                            if moves and len(moves) == expected_moves:
                                self.json_logs.append(moves)
                        except Exception:
                            pass
        print(f"Loaded {len(self.json_logs)} historical game sequences of size {self.game_size}x{self.game_size} for Reverse Curriculum.")
        
        # TensorBoard logging setup
        os.makedirs(self.args.checkpoint_dir, exist_ok=True)
        from torch.utils.tensorboard import SummaryWriter
        self.writer = SummaryWriter(log_dir=self.args.checkpoint_dir)

    def learn(self):
        """
        Training loop matching the continuous-update and baseline-evaluation approach.
        """
        starting_iteration = 1
        
        # Force 'spawn' context to safely use CUDA in worker processes
        mp_context = multiprocessing.get_context('spawn')
        
        # Reverse Curriculum Setup
        start_fill_pct = 0.70
        decay_iterations = 10
        decay_step = 0.70 / decay_iterations if decay_iterations > 0 else 0
        
        for i in range(starting_iteration, self.args.num_iters + 1):
            print(f"\n#################### Iteration {i}/{self.args.num_iters} ####################")
            
            self.writer.add_scalar("Log/Start_Sequence_Fill", start_fill_pct, i)
            
            import glob
            # Save latest model to temp file for workers to avoid 136MB IPC transfer
            temp_latest_path = os.path.join(self.args.checkpoint_dir, 'temp_latest.pth.tar')
            self.nnet.save_checkpoint(folder=self.args.checkpoint_dir, filename='temp_latest.pth.tar')
            
            # Find past checkpoints
            past_checkpoints = sorted(glob.glob(os.path.join(self.args.checkpoint_dir, 'checkpoint_*.pth.tar')))
            past_checkpoints = past_checkpoints[-5:] if past_checkpoints else []
            best_path = os.path.join(self.args.checkpoint_dir, 'best.pth.tar')
            
            # Sample random sequences for each episode
            if self.json_logs and start_fill_pct >= 0.001:
                sampled_sequences = [random.choice(self.json_logs) for _ in range(self.args.num_eps)]
            else:
                sampled_sequences = [None] * self.args.num_eps
            
            worker_args_list = []
            for seq in sampled_sequences:
                r = random.random()
                if r < 0.50:
                    opp_type, opp_path = "self", None
                elif r < 0.65:
                    opp_type, opp_path = ("best", best_path) if os.path.exists(best_path) else ("self", None)
                elif r < 0.80:
                    opp_type, opp_path = ("past", random.choice(past_checkpoints)) if past_checkpoints else ("self", None)
                elif r < 0.90:
                    opp_type, opp_path = "alpha_beta_0.1s", None
                else:
                    opp_type, opp_path = "mcts_0.1s", None
                    
                worker_args_list.append((self.game_size, temp_latest_path, self.MCTS, self.args, seq, start_fill_pct, opp_type, opp_path))
            
            # 1. Self-Play (Parallelized)
            print(f"------------ Self-Play (Fill: {start_fill_pct*100:.1f}%) ------------")
            iteration_data = []
            episode_lengths = []
            episode_depths = []
            
            with concurrent.futures.ProcessPoolExecutor(max_workers=8, mp_context=mp_context) as executor:
                futures = [executor.submit(worker_execute_episode, arg) for arg in worker_args_list]
                for future in tqdm(concurrent.futures.as_completed(futures), total=self.args.num_eps, desc="Self Play"):
                    examples, length, depth = future.result()
                    iteration_data.append(examples)
                    episode_lengths.append(length)
                    episode_depths.append(depth)
                
            # Log SelfPlay Metrics
            avg_length = sum(episode_lengths) / len(episode_lengths) if episode_lengths else 0
            avg_depth = sum(episode_depths) / len(episode_depths) if episode_depths else 0
            self.writer.add_scalar('Log/Game_Length', avg_length, i)
            self.writer.add_scalar('Log/Average_Tree_Depth', avg_depth, i)
            
            # 2. Augment Data & Add to Memory
            augmented_data = self.augment_data(iteration_data)
            flat_data = [example for game in augmented_data for example in game]
            self.memory.extend(flat_data)
            
            self.writer.add_scalar('Log/Memory_Size', len(self.memory), i)
            
            # 3. Neural Network Training
            print("\n---------- Neural Network Training -----------")
            pi_loss, v_loss, total_loss = self.nnet.train(list(self.memory))
            
            self.writer.add_scalar('Log/Policy_Loss', pi_loss, i)
            self.writer.add_scalar('Log/Value_Loss', v_loss, i)
            self.writer.add_scalar('Log/Total_Loss', total_loss, i)
            
            # 4. Model Comparison (Parallelized)
            print("\n-------------- Model Comparison (Multiprocessing) --------------")
            
            pwins, plosses, pdraws = 0, 0, 0
            
            pbuffer = io.BytesIO()
            torch.save(self.pnet.nnet.state_dict(), pbuffer)
            pnet_bytes = pbuffer.getvalue()
            
            # a. Play against Previous Network
            print("Pitting against Previous Network (pnet)...")
            half_games = self.args.arena_games // 2
            match_args_pnet = []
            for idx in range(self.args.arena_games):
                p1_starts = idx < half_games
                match_args_pnet.append((self.game_size, temp_latest_path, pnet_bytes, self.MCTS, self.args, p1_starts, "pnet"))
                
            with concurrent.futures.ProcessPoolExecutor(max_workers=8, mp_context=mp_context) as executor:
                futures = [executor.submit(worker_play_single, arg) for arg in match_args_pnet]
                for future in tqdm(concurrent.futures.as_completed(futures), total=self.args.arena_games, desc="Vs PNet"):
                    res = future.result()
                    if res == 1: pwins += 1
                    elif res == -1: plosses += 1
                    else: pdraws += 1
            
            # Decay Curriculum
            start_fill_pct = max(0.0, start_fill_pct - decay_step)
            
            print(f"\nIteration {i} complete. Vs PNet -> Wins: {pwins} | Losses: {plosses} | Draws: {pdraws}")
            
            total_decisive = pwins + plosses
            win_rate_vs_old = pwins / total_decisive if total_decisive > 0 else 0.5
            self.writer.add_scalar('Evaluation/Win_Rate_Vs_Old', win_rate_vs_old, i)
            
            if total_decisive > 0 and win_rate_vs_old >= self.args.update_threshold:
                print("ACCEPTING NEW MODEL")
                self.pnet.nnet.load_state_dict(self.nnet.nnet.state_dict())
                self.nnet.save_checkpoint(folder=self.args.checkpoint_dir, filename='best.pth.tar')
            else:
                print("REJECTING NEW MODEL")
                self.nnet.nnet.load_state_dict(self.pnet.nnet.state_dict())
                
            # b. Play against Evaluators
            eval_opponents = {
                "random": "Random",
                "alpha_beta_0.1s": "AlphaBeta_0.1s",
                "mcts_0.1s": "MCTS_0.1s"
            }
            
            for opp_type, opp_name in eval_opponents.items():
                print(f"Pitting against {opp_name}...")
                ewins, elosses, edraws = 0, 0, 0
                eval_games = 10
                match_args_eval = []
                for idx in range(eval_games):
                    p1_starts = idx < (eval_games // 2)
                    match_args_eval.append((self.game_size, temp_latest_path, None, self.MCTS, self.args, p1_starts, opp_type))
                    
                with concurrent.futures.ProcessPoolExecutor(max_workers=8, mp_context=mp_context) as executor:
                    futures = [executor.submit(worker_play_single, arg) for arg in match_args_eval]
                    for future in tqdm(concurrent.futures.as_completed(futures), total=eval_games, desc=f"Vs {opp_name}"):
                        res = future.result()
                        if res == 1: ewins += 1
                        elif res == -1: elosses += 1
                        else: edraws += 1
                        
                print(f"Vs {opp_name} -> Wins: {ewins} | Losses: {elosses} | Draws: {edraws}")
                
                eval_decisive = ewins + elosses
                win_rate_vs_eval = ewins / eval_decisive if eval_decisive > 0 else 0.5
                self.writer.add_scalar(f'Evaluation/Win_Rate_Vs_{opp_name}', win_rate_vs_eval, i)
            
            # 5. Save Checkpoints
            print("\\nSaving Checkpoint...")
            self.nnet.save_checkpoint(folder=self.args.checkpoint_dir, filename=f'checkpoint_{i}.pth.tar')
            self.writer.flush()

    @staticmethod
    def augment_data(train_examples_per_game: list):
        data_augmented = []
        from game import DotsAndBoxesGame
        for train_examples in train_examples_per_game:
            train_examples_augmented = []
            for lines, boxes, p, v in train_examples:
                train_examples_augmented.extend(zip(
                    DotsAndBoxesGame.get_rotations_and_reflections_lines(lines),
                    DotsAndBoxesGame.get_rotations_and_reflections_boxes(boxes),
                    DotsAndBoxesGame.get_rotations_and_reflections_lines(np.asarray(p)),
                    [v] * 8
                ))
            
            formatted_augmented = []
            for aug_lines, aug_boxes, aug_p, aug_v in train_examples_augmented:
                h, v_mat = DotsAndBoxesGame.l_to_h_v(aug_lines)
                size = DotsAndBoxesGame.n_lines_to_size(len(aug_lines))
                
                c1 = np.zeros((size+1, size+1))
                c1[:size+1, :size] = h
                
                c2 = np.zeros((size+1, size+1))
                c2[:size, :size+1] = v_mat
                
                c3 = np.zeros((size+1, size+1))
                c3[:size, :size] = (aug_boxes == 1).astype(float)
                
                c4 = np.zeros((size+1, size+1))
                c4[:size, :size] = (aug_boxes == -1).astype(float)
                
                board_state = np.stack([c1, c2, c3, c4])
                formatted_augmented.append((board_state, aug_p, aug_v))
                
            data_augmented.append(formatted_augmented)

        return data_augmented