import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import sys
import time
import torch
import numpy as np
from collections import deque

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PROJECT_ROOT)

import config
import model_manager
import replay_manager
import evaluator
from game import DotsAndBoxesGame
from model import NNetWrapper, dotdict
from torch.utils.tensorboard import SummaryWriter
from pretrained import run_pretraining

# Re-use args from config (augmented with model architecture defaults)
train_args = dotdict({
    'lr': config.LEARNING_RATE,
    'epochs': config.EPOCHS,
    'batch_size': config.BATCH_SIZE,
    'num_channels': 256,
    'num_res_blocks': 10,
    'l2_reg': 1e-4,
    # 7 iter/hour × 48 hours = 336 total iterations → LR reaches eta_min exactly at stop time
    'lr_scheduler_steps': 336,
    'device': 'cuda' if torch.cuda.is_available() else 'cpu'
})

def train_network(replay_data, output_model_path, nnet, epochs=None):
    """
    Train AlphaZero network.
    
    Input:
        replay_data: merged self-play games (loaded as tuples)
        output_model_path: path to save trained model
        nnet: the single persistent instance of the Neural Network
        epochs: number of epochs to train
    """
        
    print(f"Training on {len(replay_data)} raw samples (augmenting on-the-fly)...")
    pi_loss, v_loss, total_loss, entropy = nnet.train(replay_data, epochs=epochs)
    
    print(f"Training complete. Loss -> Policy: {pi_loss:.4f} | Value: {v_loss:.4f} | Total: {total_loss:.4f} | Entropy: {entropy:.4f}")
    
    # Save the trained candidate model
    os.makedirs(os.path.dirname(output_model_path), exist_ok=True)
    model_manager.save_latest_model(nnet)
    print(f"Candidate model saved to {output_model_path}")
    
    return {"pi_loss": pi_loss, "v_loss": v_loss, "total_loss": total_loss, "entropy": entropy}

def load_training_checkpoint():
    """Resume interrupted training. (Currently handled dynamically in train_network)"""
    pass

def save_training_checkpoint():
    """Save training states. (Currently handled by model_manager.save_latest_model)"""
    pass

def run_training_iteration(writer=None, iteration=0, nnet=None, replay_buffer=None):
    """
    Execute one complete iteration:
    1. Validate and promote incoming → ready
    2. Claim ready → training (anti-race)
    3. Load replay buffer from training/
    4. Train candidate network
    5. Evaluate candidate vs best
    6. Mark training files as used
    """
    print("\n" + "="*60)
    print("STARTING NEW TRAINING ITERATION", iteration)
    print("="*60)
    
    # 1. Validate and promote incoming files to ready
    promoted = replay_manager.validate_and_promote()
    print(f"Promoted {len(promoted)} new files to ready/")
    
    # 2. Claim files atomically to prevent race conditions
    claimed_files = replay_manager.claim_for_training()
    if not claimed_files:
        print("No files in ready/ to claim. Trainer acting as fallback worker to generate 50 games...")
        from selfplay import SelfPlayGenerator
        import shutil
        
        generator = SelfPlayGenerator()
        candidate_path = os.path.join(config.get_current_model_dir(), "checkpoint_candidate.pth.tar")
        if not os.path.exists(candidate_path):
            candidate_path = model_manager.get_best_model_path()
            
        if os.path.exists(candidate_path):
            generator.load_model(candidate_path)
            
        replay_file = generator.play_games(
            num_games=50,
            save_dir=config.REPLAY_READY,
            worker_id="trainer_fallback",
            model_version=iteration,
            current_phase=model_manager.get_current_phase(),
            epoch=model_manager.get_phase_iteration()
        )
        if replay_file and os.path.exists(replay_file):
            print(f"Trainer fallback generated {replay_file}.")
            fname = os.path.basename(replay_file)
            dest = os.path.join(config.REPLAY_TRAINING, fname)
            shutil.move(replay_file, dest)
            claimed_files.append(dest)
        else:
            print("Trainer fallback failed to generate games.")
            return False
        
    # 2.5 Check Curriculum Phase Winrates
    client_winrates = []
    current_server_phase = model_manager.get_current_phase()
    phase_iterations = model_manager.get_phase_iteration()
    phase_advanced = False
    
    import json
    aggregated_bot_stats = {}
    
    for f in claimed_files:
        try:
            data = np.load(f, allow_pickle=False)
            if 'phase_winrate' in data and 'current_phase' in data:
                file_phase = data['current_phase'][0]
                # Only use winrates generated by clients running the CURRENT phase
                if file_phase == current_server_phase:
                    client_winrates.append(data['phase_winrate'][0])
                    
            if 'bot_stats' in data:
                bot_stats_str = str(data['bot_stats'][0])
                file_bot_stats = json.loads(bot_stats_str)
                for opp, stats in file_bot_stats.items():
                    if opp not in aggregated_bot_stats:
                        aggregated_bot_stats[opp] = {'games': 0, 'wins': 0, 'decisive': 0}
                    aggregated_bot_stats[opp]['games'] += stats['games']
                    aggregated_bot_stats[opp]['wins'] += stats['wins']
                    aggregated_bot_stats[opp]['decisive'] += stats['decisive']
                    
        except Exception as e:
            print(f"Error parsing {f}: {e}")
            pass
            
    if client_winrates:
        max_client_winrate = max(client_winrates)
        current_phase = model_manager.get_current_phase()
        print ("max_client_winrate ,current_phase",max_client_winrate ,current_phase)
        if writer:
            writer.add_scalar('Curriculum/Phase_Winrate', max_client_winrate, iteration)
            writer.add_scalar('Training_Winrate', max_client_winrate, iteration)
            writer.add_scalar('Curriculum/Current_Phase', current_phase, iteration)
            
            # Log Bot Stats
            total_games_all_bots = sum(s['games'] for s in aggregated_bot_stats.values())
            for opp, stats in aggregated_bot_stats.items():
                if total_games_all_bots > 0:
                    pct = stats['games'] / total_games_all_bots
                    writer.add_scalar(f'Curriculum_Bots_count/{opp}_Percentage', pct, iteration)
                if stats['decisive'] > 0:
                    wr = stats['wins'] / stats['decisive']
                    writer.add_scalar(f'Curriculum_Bots_Winrate/{opp}_WinRate', wr, iteration)
            
        # Advance phase only when the model is genuinely winning, 
        # with a backstop of 20 iterations so training never stalls forever.
        threshold = config.PHASE_ADVANCE_THRESHOLD.get(current_phase, 0.60)
        
        # Only check activate next phase after this 10 filled game epoch 
        # (actual winrate when the game starting from scratch)
        if phase_iterations >= 10:
            if (max_client_winrate >= threshold ) and current_phase < len(config.PHASES_CONFIG) - 1:
                reason = f"Winrate {max_client_winrate:.1%} >= {threshold:.0%}" if max_client_winrate >= threshold else "Max phase iterations reached"
                print(f"\n===========================================================")
                print(f"Phase {current_phase} cleared ({reason})!")
                print(f"Advancing to Phase {current_phase + 1}...")
                print(f"===========================================================\n")
                model_manager.advance_curriculum_phase()
                phase_advanced = True
        
    # 3. Load the replay buffer from training/
    new_data = replay_manager.load_replay_buffer(claimed_files)
    
    is_first_time = (replay_buffer is None) or (len(replay_buffer) == 0)
    
    if is_first_time and len(new_data) < config.MIN_REPLAY_SIZE:
        print(f"New data size ({len(new_data)}) below minimum ({config.MIN_REPLAY_SIZE}). Waiting...")
        # Move claimed files back to ready/ so they aren't lost
        for f in claimed_files:
            fname = os.path.basename(f)
            import shutil
            shutil.move(f, os.path.join(config.REPLAY_READY, fname))
        return False
    
    # Accumulate into rolling replay buffer (experience replay window)
    if replay_buffer is not None:
        # Snapshot the old buffer BEFORE extending — avoids numpy ambiguous
        # truth-value errors that happen when using "s not in new_data" on
        # tuples containing numpy arrays.
        old_data = list(replay_buffer)
        replay_buffer.extend(new_data)

        # Freshness bias: 70% of training batch from the newest data,
        # 30% from the older rolling buffer. This prevents stale Phase-0
        # data from dominating when the model has already advanced phases.
        import random as _rnd
        n_total = min(len(replay_buffer), config.MAX_REPLAY_SIZE)
        n_fresh = min(int(n_total * 0.70), len(new_data))
        n_old   = min(n_total - n_fresh, len(old_data))
        fresh_sample = _rnd.sample(new_data, n_fresh) if n_fresh < len(new_data) else list(new_data)
        old_sample   = _rnd.sample(old_data,  n_old)  if n_old  < len(old_data)  else old_data
        replay_data  = fresh_sample + old_sample
        _rnd.shuffle(replay_data)
        print(f"Replay buffer: {len(new_data)} new + {len(old_data)} retained → "
              f"training on {len(fresh_sample)} fresh + {len(old_sample)} old = {len(replay_data)} samples")
    else:
        replay_data = new_data

    # 4. Train candidate network
    merged_path = replay_manager.merge_replay(claimed_files)
    candidate_path = os.path.join(config.get_current_model_dir(), "checkpoint_candidate.pth.tar")
    dynamic_epochs = 2 * len(claimed_files)
    losses = train_network(replay_data, candidate_path, nnet, epochs=dynamic_epochs)
    
    if writer:
        current_lr = nnet.optimizer.param_groups[0]['lr']
        writer.add_scalar('Log/Policy_Loss', losses["pi_loss"], iteration)
        writer.add_scalar('Log/Value_Loss', losses["v_loss"], iteration)
        writer.add_scalar('Log/Total_Loss', losses["total_loss"], iteration)
        writer.add_scalar('Log/Policy_Entropy', losses["entropy"], iteration)
        writer.add_scalar('Log/Memory_Size', len(replay_data), iteration)
        writer.add_scalar('Log/Learning_Rate', current_lr, iteration)
    
    # 5. Evaluate and update
    print("\nEvaluating candidate model against best model and baselines...")
    promoted_model, win_rate, baseline_win_rates, avg_depth = evaluator.evaluate_new_model(iteration)
    
    if writer:
        if win_rate is not None:
            writer.add_scalar('Evaluation/Win_Rate_Vs_Old', win_rate, iteration)
            writer.add_scalar('Evaluation/MCTS_Avg_Depth', avg_depth, iteration)
        for opp_name, rate in baseline_win_rates.items():
            writer.add_scalar(f'Evaluation/Win_Rate_Vs_{opp_name}', rate, iteration)
        writer.flush()
    
    if promoted_model:
        print("Model promoted! Cleaning up old data...")
        # Invalidate the persistent self-play executor so workers reload
        # the newly promoted model on the next self-play batch. Without
        # this, workers keep using the pre-promotion weights indefinitely.
        try:
            import coach as _coach
            if _coach._SELFPLAY_EXECUTOR is not None:
                print("Shutting down stale self-play executor so workers reload new model...")
                _coach._SELFPLAY_EXECUTOR.shutdown(wait=False, cancel_futures=True)
                _coach._SELFPLAY_EXECUTOR = None
                _coach._SELFPLAY_EXECUTOR_MODEL_SIGNATURE = None
                _coach._SELFPLAY_EXECUTOR_MAX_WORKERS = None
        except Exception as _e:
            print(f"Warning: could not reset self-play executor: {_e}")

    # 6. Mark files as used
    replay_manager.mark_used(claimed_files)
    
    # Increment phase iteration if we didn't advance the phase this round
    if not phase_advanced:
        model_manager.increment_phase_iteration()
    
    # 7. Maintain disk space
    replay_manager.cleanup_old(days=7)
    
    return True

def training_loop(load_checkpoint=None):
    """
    Main infinite training loop.
    Monitors replay files and runs iterations continuously.
    """
    print("Distributed Trainer Daemon Started. Monitoring storage/replay...")
    
    # Initialize TensorBoard writer
    log_dir = config.get_current_model_dir()
    os.makedirs(log_dir, exist_ok=True)
    writer = SummaryWriter(log_dir=log_dir)
    iteration = 1
    
    # Backup source code for reproducibility
    import glob
    import shutil
    code_dir = os.path.join(log_dir, 'code')
    os.makedirs(code_dir, exist_ok=True)
    
    for f in glob.glob(os.path.join(PROJECT_ROOT, '*.py')):
        shutil.copy(f, code_dir)
        
    dist_dir = os.path.join(code_dir, 'distributed')
    os.makedirs(dist_dir, exist_ok=True)
    for f in glob.glob(os.path.join(PROJECT_ROOT, 'distributed', '*.py')):
        shutil.copy(f, dist_dir)
        
    bots_src = os.path.join(PROJECT_ROOT, 'bots')
    if os.path.exists(bots_src):
        shutil.copytree(bots_src, os.path.join(code_dir, 'bots'), dirs_exist_ok=True)
    
    # Initialize the neural network ONCE for continuous use
    print("Initializing Neural Network for continuous training...")
    dummy_game = DotsAndBoxesGame(size=5)
    global_nnet = NNetWrapper(dummy_game, train_args)

    # ── Supervised pretraining disabled ──
    print("\n" + "=" * 60)
    print("PHASE 0: PRETRAINING DISABLED - STARTING FROM SCRATCH")
    print("=" * 60)
    # did_pretrain = run_pretraining(global_nnet, log_dir, writer)
    # if did_pretrain:
    #     print("[Pretrain] Pretraining complete. Proceeding to AlphaZero self-play.\n")
    # else:
    #     print("[Pretrain] Pretraining skipped. Using existing weights.\n")
        
    # Signal to workers that pretraining is done (or not needed)
    model_manager.set_pretrain_finished()

    
    # Try to load full checkpoint (weights + optimizer + scheduler state)
    if load_checkpoint and os.path.exists(load_checkpoint):
        load_path = load_checkpoint
        print(f"Loading specifically requested checkpoint from {load_checkpoint}")
    else:
        candidate_path = os.path.join(config.get_current_model_dir(), "checkpoint_candidate.pth.tar")
        if os.path.exists(candidate_path):
            load_path = candidate_path
            print("Load pretrained model checkpoint_candidate")
        else:
            load_path = model_manager.get_latest_model_path()
        
    if os.path.exists(load_path):
        checkpoint = torch.load(load_path, map_location='cpu', weights_only=False)
        weights = checkpoint.get('state_dict', checkpoint)
        global_nnet.nnet.load_state_dict(weights)
        if 'optimizer' in checkpoint:
            global_nnet.optimizer.load_state_dict(checkpoint['optimizer'])
            print(f"Restored optimizer state from {load_path}.")
        if 'scheduler' in checkpoint:
            global_nnet.scheduler.load_state_dict(checkpoint['scheduler'])
            print(f"Restored scheduler state from {load_path}.")
        else:
            # No saved scheduler state (pre-scheduler checkpoint).
            # Fast-forward the scheduler to match iterations already completed
            # so LR resumes from the correct position instead of restarting at peak.
            elapsed = model_manager.get_current_version()
            for _ in range(elapsed):
                global_nnet.scheduler.step()
            resumed_lr = global_nnet.optimizer.param_groups[0]['lr']
            print(f"No scheduler state found. Fast-forwarded {elapsed} steps. Resumed LR: {resumed_lr:.2e}")
        print(f"Loaded model weights from {load_path}.")
    else:
        print("No previous model found. Initializing randomly.")
        
    # CRITICAL: Save the model (whether loaded or randomly initialized) to disk
    # so that the fallback generator and remote workers pick up these exact weights
    # before they generate the first batch of self-play games.
    print("Synchronizing loaded/initial model to disk for workers...")
    model_manager.save_latest_model(global_nnet)
    best_path = model_manager.get_best_model_path()
    candidate_path = os.path.join(config.get_current_model_dir(), "checkpoint_candidate.pth.tar")
    checkpoint0_path = os.path.join(config.get_current_model_dir(), "checkpoint_0.pth.tar")
    import shutil
    shutil.copyfile(candidate_path, best_path)
    shutil.copyfile(candidate_path, checkpoint0_path)
    

    # Initialize rolling experience replay buffer capped at MAX_REPLAY_SIZE
    print(f"Initializing experience replay buffer (max size: {config.MAX_REPLAY_SIZE:,})...")
    replay_buffer = deque(maxlen=config.MAX_REPLAY_SIZE)
    
    print("PHASE 1: ALPHA ZERO TRAINING")

    while True:
        try:
            # Check how many replay files are in incoming/ and ready/
            success = run_training_iteration(writer, iteration, global_nnet, replay_buffer)
            if not success:
                print("Iteration skipped. Sleeping 60s...")
                time.sleep(60)
            else:
                iteration += 1
                
        except Exception as e:
            print(f"Error during training iteration: {e}")
            import traceback
            traceback.print_exc()
            time.sleep(30)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Distributed AlphaZero Trainer")
    parser.add_argument("--pretrained_path", type=str, default=None, 
                        help="Specific checkpoint path to load and resume training from.")
    args = parser.parse_args()
    
    training_loop(load_checkpoint=args.pretrained_path)